apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-data
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi