server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location /api/dotnet {
        proxy_pass http://10.1.0.226:8083;
    }
    
    location /api/python {
        proxy_pass http://10.1.0.226:8084;
    }
    
    location /api/go {
        proxy_pass http://10.1.0.226:8085;
    }
}