"""discover — crawl a site (SPA-aware) and emit a starter target profile.

Safe by construction: GET-only, polite rate, same-origin only.
"""
from __future__ import annotations

import asyncio
import re
import time
from collections import deque
from urllib.parse import urljoin, urlsplit

from .base import ModuleContext, register

A_HREF = re.compile(r"<a[^>]+href=[\"']([^\"'#]+)", re.I)
TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
SRC_JS = re.compile(r"<script[^>]+src=[\"']([^\"']+\.js)[\"']", re.I)
META_GEN = re.compile(r"<meta[^>]+name=[\"']generator[\"'][^>]+content=[\"']([^\"']+)", re.I)

COMMON_FILES = [
    "robots.txt", "sitemap.xml", "security.txt", ".well-known/security.txt",
    "favicon.ico", "manifest.json", "sw.js",
]

TECH_HINTS = {
    "server": ("Server",),
    "x-powered-by": ("X-Powered-By",),
    "via": ("Via", "X-Cache"),
}


@register("discover", help="Crawl site structure and generate a starter target profile")
async def run(ctx: ModuleContext):
    from ..core.util import make_client, TokenBucket, is_trace

    rep = ctx.reporter
    base = ctx.target.base_url.rstrip("/")
    bucket = TokenBucket(ctx.options.get("max_rps", 10))
    headers = dict(ctx.target.global_headers)
    seen: set[str] = set()
    queue: deque[tuple[str, str]] = deque([(base, "")])
    pages: list[dict] = []
    assets: list[str] = []
    server_headers: dict[str, str] = {}
    cap = int(ctx.options.get("max_pages", ctx.target.max_crawl_pages))

    origin = urlsplit(base)
    def same_origin(u: str) -> bool:
        p = urlsplit(u)
        return (p.scheme, p.netloc) == (origin.scheme, origin.netloc)

    async with make_client(headers=headers) as client:
        async def fetch(url: str) -> tuple[int, float, str, dict]:
            t0 = time.perf_counter()
            await bucket.take()
            try:
                r = await client.get(url)
                return r.status_code, time.perf_counter() - t0, r.text or "", dict(r.headers)
            except Exception as e:
                return -1, time.perf_counter() - t0, f"{type(e).__name__}: {e}", {}

        while queue and len(pages) < cap:
            url, via = queue.popleft()
            norm = url.split("#")[0].rstrip("/") or url
            if norm in seen or not same_origin(norm):
                continue
            seen.add(norm)
            status, dt, text, hdrs = await fetch(norm)
            if status == -1:
                rep.add(f"GET {norm}", "FAIL", detail=text[:160])
                continue
            if not server_headers:
                server_headers = {k.lower(): v for k, v in hdrs.items()}
            m = TITLE_RE.search(text)
            title = re.sub(r"\s+", " ", m.group(1)).strip()[:100] if m else ""
            trace = is_trace(text)
            status_label = "PASS" if status == 200 else "WARN"
            detail = f"status={status} {dt*1000:.0f}ms bytes={len(text)} via={via or 'seed'}"
            if trace:
                status_label, detail = "FAIL", detail + f" TRACE:{trace}"
            rep.add(f"page {norm}", status_label, detail=detail,
                    data={"ms": round(dt * 1000), "bytes": len(text)})
            pages.append({"url": norm, "status": status, "ms": round(dt * 1000), "title": title})
            for js in SRC_JS.findall(text)[:10]:
                ju = urljoin(norm, js)
                if same_origin(ju) and ju not in assets:
                    assets.append(ju)
            for href in A_HREF.findall(text)[:80]:
                u = urljoin(norm, href.strip())
                if same_origin(u.split("#")[0]) and u not in seen:
                    queue.append((u.split("#")[0], norm))
        # common files
        for f in COMMON_FILES:
            status, dt, _, _ = await fetch(f"{base}/{f}")
            if status == 200:
                rep.add(f"file /{f}", "WARN", detail="exists (informational)")

    rep.metric("pages_crawled", len(pages))
    rep.metric("js_assets", len(assets))
    for k in ("server", "x-powered-by"):
        if k in server_headers:
            rep.add(f"tech:{k}", "PASS", detail=server_headers[k])

    # emit starter profile
    out_path = ctx.options.get("out") or "omnitest/targets/discovered_profile.py"
    slug = re.sub(r"[^a-z0-9]+", "_", host_of(base)).strip("_")
    routes = "\n".join(f'        "{p["url"]}",' for p in pages[:40])
    skeleton = f'''"""Starter profile generated by OMNITEST discover at {time.strftime('%F %T')}."""
from omnitest.core.config import Target

TARGET = Target(
    name="{slug}",
    base_url="{base}",
    seed_paths=[
{routes}
    ],
    authorized_domains=[],   # TODO: list hosts covered by your signed authorization
    notes="Generated by discover; fill endpoints/login before heavy modules.",
)
'''
    try:
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(skeleton)
        rep.artifacts.append(out_path)
        rep.add("profile emitted", "PASS", detail=out_path)
    except OSError as e:
        rep.add("profile emit", "FAIL", detail=str(e))


def host_of(url: str) -> str:
    return urlsplit(url).netloc
