#!/bin/bash
# 生成完整的 web 部署 YAML

echo "apiVersion: apps/v1"
echo "kind: Deployment"
echo "metadata:"
echo "  name: ai-character-web"
echo "  labels:"
echo "    app: ai-character-web"
echo "spec:"
echo "  replicas: 1"
echo "  selector:"
echo "    matchLabels:"
echo "      app: ai-character-web"
echo "  template:"
echo "    metadata:"
echo "      labels:"
echo "        app: ai-character-web"
echo "    spec:"
echo "      containers:"
echo "      - name: nginx"
echo "        image: nginx:alpine"
echo "        ports:"
echo "        - containerPort: 80"
echo "        volumeMounts:"
echo "        - name: html"
echo "          mountPath: /usr/share/nginx/html/index.html"
echo "          subPath: index.html"
echo "      volumes:"
echo "      - name: html"
echo "        configMap:"
echo "          name: ai-character-html"
echo "---"
echo "apiVersion: v1"
echo "kind: ConfigMap"
echo "metadata:"
echo "  name: ai-character-html"
echo "data:"
echo "  index.html: |"
# 将 HTML 内容转成 YAML 格式（每行缩进 4 空格）
sed 's/^/    /' ai-character.html
echo "---"
echo "apiVersion: v1"
echo "kind: Service"
echo "metadata:"
echo "  name: ai-character-svc"
echo "spec:"
echo "  selector:"
echo "    app: ai-character-web"
echo "  ports:"
echo "  - port: 80"
echo "    targetPort: 80"
echo "  type: ClusterIP"
