services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    stdin_open: true
    tty: true
    mem_limit: 512m
    cpus: 1
    volumes:
      - ./work:/root/work
    working_dir: /root/work
    network_mode: host
    command: /bin/bash
